### ISSUE TITLE
[oauth] Implement OAuth for authentication routes

### ISSUE THREAD

**Issue by slothelle** [ArtCraftCode/ravelry#8]
Yup.

**Comment by meltar** [comment]
Ravelry should support OAuth1 and OAuth2.  Do you want to use OAuth2?

**Comment by slothelle** [comment]
Probably 2 since 1 will likely eventually be phased out

**Comment by meltar** [comment]
Sounds good.  I'd like to work on this one.  I've worked with OAuth2 before in a couple of apps.

**Comment by slothelle** [comment]
Get it girl! I'd recommend checking the API docs to see what calls need to
be authenticated. Ideally something that can be used for every
authenticated call would be amazing

On Thursday, February 20, 2014, Melissa notifications@github.com wrote:

> Sounds good. I'd like to work on this one. I've worked with OAuth2 before
> in a couple of apps.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/feministy/ravelry/issues/8#issuecomment-35684037
> .

## 

Liz Abinante
eabinante@gmail.com
www.lizabinante.com
www.github.com/feministy
(530) 220-3751
@feministy

**Comment by meltar** [comment]
I started a new job (Rails!) this week, and I have meetups tonight and tomorrow, so I'm pretty busy.  I want to work on this on Friday and Saturday (or Thursday if I'm lucky), but if that's too slow, feel free to do it.  I don't want to hold you back.

**Comment by slothelle** [comment]
No no - not too slow at all. I only work on this a few hours a week :)

**Comment by meltar** [comment]
I finally got my api key, so now I can play with authentication. :sparkles: 

I'd still like to chat about your design plans at some point, but I'll start building a client class to deal with a user's account authorization, token, scopes, etc in one place.  If you want anything changed, I can always redo/refactor.

**Comment by outcassed** [comment]
(psst - We only support OAuth 1 right now and no plans to add 2.0 in the immediate future)

**Comment by meltar** [comment]
@caseyf that's good to know. I remember reading that about OAuth1 a while ago, but I thought I saw something about using both recently.  Maybe I'm thinking of another project.

**Comment by outcassed** [comment]
ah! Yep - you definitely could have read it in the forums somewhere. We once had undocumented support for one of the older drafts and I was trying to help someone use it once.  Right now I'm dragging my feet since no API users are really pushing hard for support and it seems like people are constantly finding vulnerabilities in some OAuth2 implementation (and to be honest, it's just not the most fun thing to work on)  If you ever need anything or run into some API thing that is broken or awkward you're welcome to bug @oharethey or I on github.

_Updated Sept 2015_ We've had a couple OAuth2 requests lately. I completely missed that it offers the  implicit grant flow that you can use if your client is a browser/Javascript app.

**Comment by meltar** [comment]
I have used OAuth2 a few times, but not OAuth1, so I don't mind learning more about it.  This gem is a good excuse to do more research on authentication security too.

**Comment by slothelle** [comment]
@caseyf you da best!

**Comment by slothelle** [comment]
going to try incorporating @duien's gem: https://github.com/duien/omniauth-ravelry

**Comment by duien** [comment]
I'm worries I might be the "someone" @caseyf was helping with the undocumented OAuth 2 stuff ... since my gem does mention OAuth 2. Although looking at what I'm pulling in from omniauth it looks like maybe it is OAuth 1? I have no idea anymore. Let me know if you can't make it work, I guess.

**Comment by amar47shah** [comment]
Hi, I'd like to work on this, because I would love to see a Ravelry gem. I'm not knowledgeable about OAuth but I can dig through whatever docs and example projects I can find. Does the omniauth-ravelry strategy work as-is? Is there an any working example code (a simple rack app, say) that I could play around with so I could understand it better?

**Comment by duien** [comment]
Thanks to @amar47shah the `omniauth-ravelry` gem is up to date! I just pushed a new 0.0.3 version which works with the current API. After digging in a bit, I can confirm that it's using OAuth 1.

**Comment by amar47shah** [comment]
Thanks, @duien! Could you post your sample app?

**Comment by amar47shah** [comment]
Got it @duien, thanks. https://github.com/duien/example-omniauth-ravelry
